### PR TITLE
fix(docs): follow repo url change for travis ci badge

### PR DESCRIPTION
**Pull request by yumetodo**
[Build Status](https://travis-ci.org/indexzero/node-portfinder)
↓
[Build Status](https://travis-ci.org/http-party/node-portfinder)

### CODE REVIEW

**Comment by eriktrom** [comment]
awesome thanks!

**Comment by yumetodo** [comment]
on the latest master branch(727ee4e6943ed0b25a8e1a5fb93c8ebd65729ef2), this PR is not included.

727ee4e6943ed0b25a8e1a5fb93c8ebd65729ef2 (v1.0.23)'s parent commit is 25556862945514cf890d9b8cee9020ab3bbe6c5f (v1.0.21) , not f2fa9d8a0c7144bb23ebc81269cbf92d9f462946 (v1.0.22) that is strange!

**Comment by eriktrom** [comment]
@yumetodo - yeah there was an emergency rollback - reopening and rebasing against master. 

Thanks for the followup, ur change very appreciated.

**Comment by eriktrom** [comment]
https://github.com/http-party/node-portfinder/releases/tag/v1.0.24 fyi

**Pull request merged**
